title: Brede School documentation
description: Documentation for after school program organization, a.k.a. Brede School
theme: just-the-docs

url: https://wijnandb.github.io/documentation

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
